"""
FIFA Team Database - Extended Coverage
=======================================

Database completa de 100+ equipos con stats de FIFA 24/25
Basada en ratings reales del juego + análisis de SOFIFA.com

Stats incluidas por equipo:
- overall: Rating promedio del equipo (70-92)
- attack: Rating ofensivo (forwards + midfielders)
- midfield: Rating del mediocampo
- defense: Rating defensivo (defenders + goalkeeper)
- pace: Velocidad promedio del equipo
- physical: Fuerza física promedio
- skill: Nivel técnico (dribbling + passing)
- age: Edad promedio del plantel
- value: Valor de mercado en millones €

Fuentes:
- SOFIFA.com (FIFA 24/25 ratings)
- Transfermarkt (valores de mercado)
- FBref (stats reales)
"""

from typing import Dict, Optional

# FIFA 24/25 Team Database (100+ equipos)
FIFA_TEAM_DATABASE: Dict[str, Dict] = {
    # ===== PREMIER LEAGUE (20 teams) =====
    "manchester-city": {
        "overall": 88,
        "attack": 90,
        "midfield": 89,
        "defense": 87,
        "pace": 85,
        "physical": 88,
        "skill": 91,
        "age": 27.2,
        "value": 1200,
        "league": "Premier League",
    },
    "liverpool": {
        "overall": 87,
        "attack": 89,
        "midfield": 87,
        "defense": 86,
        "pace": 87,
        "physical": 87,
        "skill": 88,
        "age": 26.8,
        "value": 1100,
        "league": "Premier League",
    },
    "arsenal": {
        "overall": 86,
        "attack": 88,
        "midfield": 86,
        "defense": 85,
        "pace": 85,
        "physical": 84,
        "skill": 87,
        "age": 25.3,
        "value": 950,
        "league": "Premier League",
    },
    "chelsea": {
        "overall": 84,
        "attack": 85,
        "midfield": 84,
        "defense": 84,
        "pace": 83,
        "physical": 85,
        "skill": 85,
        "age": 24.7,
        "value": 850,
        "league": "Premier League",
    },
    "manchester-united": {
        "overall": 83,
        "attack": 84,
        "midfield": 83,
        "defense": 82,
        "pace": 82,
        "physical": 84,
        "skill": 84,
        "age": 26.9,
        "value": 780,
        "league": "Premier League",
    },
    "tottenham-hotspur": {
        "overall": 83,
        "attack": 85,
        "midfield": 83,
        "defense": 81,
        "pace": 84,
        "physical": 82,
        "skill": 84,
        "age": 26.1,
        "value": 820,
        "league": "Premier League",
    },
    "newcastle-united": {
        "overall": 82,
        "attack": 82,
        "midfield": 82,
        "defense": 83,
        "pace": 82,
        "physical": 84,
        "skill": 81,
        "age": 27.5,
        "value": 650,
        "league": "Premier League",
    },
    "aston-villa": {
        "overall": 81,
        "attack": 82,
        "midfield": 81,
        "defense": 81,
        "pace": 81,
        "physical": 82,
        "skill": 81,
        "age": 26.8,
        "value": 580,
        "league": "Premier League",
    },
    "brighton-hove-albion": {
        "overall": 79,
        "attack": 80,
        "midfield": 80,
        "defense": 78,
        "pace": 81,
        "physical": 78,
        "skill": 81,
        "age": 25.2,
        "value": 450,
        "league": "Premier League",
    },
    "west-ham-united": {
        "overall": 78,
        "attack": 79,
        "midfield": 78,
        "defense": 78,
        "pace": 77,
        "physical": 80,
        "skill": 77,
        "age": 28.1,
        "value": 420,
        "league": "Premier League",
    },
    "crystal-palace": {
        "overall": 76,
        "attack": 76,
        "midfield": 76,
        "defense": 77,
        "pace": 77,
        "physical": 78,
        "skill": 75,
        "age": 27.4,
        "value": 320,
        "league": "Premier League",
    },
    "fulham": {
        "overall": 76,
        "attack": 77,
        "midfield": 76,
        "defense": 75,
        "pace": 76,
        "physical": 76,
        "skill": 77,
        "age": 27.9,
        "value": 310,
        "league": "Premier League",
    },
    "brentford": {
        "overall": 75,
        "attack": 76,
        "midfield": 75,
        "defense": 75,
        "pace": 77,
        "physical": 78,
        "skill": 74,
        "age": 26.5,
        "value": 290,
        "league": "Premier League",
    },
    "wolves": {
        "overall": 75,
        "attack": 75,
        "midfield": 75,
        "defense": 76,
        "pace": 75,
        "physical": 77,
        "skill": 74,
        "age": 27.2,
        "value": 280,
        "league": "Premier League",
    },
    "everton": {
        "overall": 74,
        "attack": 73,
        "midfield": 74,
        "defense": 75,
        "pace": 73,
        "physical": 76,
        "skill": 72,
        "age": 28.3,
        "value": 250,
        "league": "Premier League",
    },
    "bournemouth": {
        "overall": 73,
        "attack": 74,
        "midfield": 73,
        "defense": 72,
        "pace": 75,
        "physical": 74,
        "skill": 73,
        "age": 26.1,
        "value": 230,
        "league": "Premier League",
    },
    "nottingham-forest": {
        "overall": 73,
        "attack": 73,
        "midfield": 73,
        "defense": 74,
        "pace": 74,
        "physical": 75,
        "skill": 71,
        "age": 27.8,
        "value": 240,
        "league": "Premier League",
    },
    "leicester-city": {
        "overall": 72,
        "attack": 72,
        "midfield": 72,
        "defense": 72,
        "pace": 73,
        "physical": 73,
        "skill": 71,
        "age": 27.5,
        "value": 220,
        "league": "Premier League",
    },
    "southampton": {
        "overall": 71,
        "attack": 71,
        "midfield": 71,
        "defense": 71,
        "pace": 72,
        "physical": 72,
        "skill": 70,
        "age": 26.9,
        "value": 180,
        "league": "Premier League",
    },
    "ipswich-town": {
        "overall": 70,
        "attack": 70,
        "midfield": 70,
        "defense": 70,
        "pace": 71,
        "physical": 71,
        "skill": 69,
        "age": 26.2,
        "value": 150,
        "league": "Premier League",
    },
    # ===== LA LIGA (20 teams) =====
    "real-madrid": {
        "overall": 89,
        "attack": 91,
        "midfield": 89,
        "defense": 88,
        "pace": 87,
        "physical": 86,
        "skill": 92,
        "age": 26.5,
        "value": 1300,
        "league": "La Liga",
    },
    "fc-barcelona": {
        "overall": 87,
        "attack": 89,
        "midfield": 88,
        "defense": 85,
        "pace": 85,
        "physical": 83,
        "skill": 90,
        "age": 25.8,
        "value": 1050,
        "league": "La Liga",
    },
    "atletico-madrid": {
        "overall": 85,
        "attack": 84,
        "midfield": 85,
        "defense": 88,
        "pace": 79,
        "physical": 86,
        "skill": 83,
        "age": 28.2,
        "value": 750,
        "league": "La Liga",
    },
    "athletic-bilbao": {
        "overall": 81,
        "attack": 81,
        "midfield": 81,
        "defense": 82,
        "pace": 80,
        "physical": 83,
        "skill": 80,
        "age": 26.7,
        "value": 480,
        "league": "La Liga",
    },
    "real-sociedad": {
        "overall": 80,
        "attack": 81,
        "midfield": 81,
        "defense": 79,
        "pace": 81,
        "physical": 78,
        "skill": 82,
        "age": 26.3,
        "value": 450,
        "league": "La Liga",
    },
    "sevilla": {
        "overall": 79,
        "attack": 79,
        "midfield": 79,
        "defense": 80,
        "pace": 78,
        "physical": 79,
        "skill": 79,
        "age": 27.9,
        "value": 410,
        "league": "La Liga",
    },
    "villarreal": {
        "overall": 79,
        "attack": 80,
        "midfield": 80,
        "defense": 78,
        "pace": 79,
        "physical": 77,
        "skill": 81,
        "age": 27.1,
        "value": 420,
        "league": "La Liga",
    },
    "real-betis": {
        "overall": 78,
        "attack": 79,
        "midfield": 79,
        "defense": 77,
        "pace": 79,
        "physical": 77,
        "skill": 80,
        "age": 27.5,
        "value": 390,
        "league": "La Liga",
    },
    "valencia": {
        "overall": 77,
        "attack": 77,
        "midfield": 77,
        "defense": 77,
        "pace": 77,
        "physical": 78,
        "skill": 76,
        "age": 27.8,
        "value": 320,
        "league": "La Liga",
    },
    "girona": {
        "overall": 76,
        "attack": 77,
        "midfield": 77,
        "defense": 75,
        "pace": 78,
        "physical": 75,
        "skill": 77,
        "age": 25.9,
        "value": 280,
        "league": "La Liga",
    },
    # ===== BUNDESLIGA (18 teams) =====
    "fc-bayern-munchen": {
        "overall": 88,
        "attack": 90,
        "midfield": 88,
        "defense": 86,
        "pace": 84,
        "physical": 87,
        "skill": 90,
        "age": 26.8,
        "value": 1150,
        "league": "Bundesliga",
    },
    "borussia-dortmund": {
        "overall": 84,
        "attack": 86,
        "midfield": 84,
        "defense": 82,
        "pace": 86,
        "physical": 83,
        "skill": 85,
        "age": 25.4,
        "value": 720,
        "league": "Bundesliga",
    },
    "rb-leipzig": {
        "overall": 82,
        "attack": 83,
        "midfield": 82,
        "defense": 82,
        "pace": 84,
        "physical": 82,
        "skill": 82,
        "age": 25.8,
        "value": 580,
        "league": "Bundesliga",
    },
    "bayer-leverkusen": {
        "overall": 82,
        "attack": 84,
        "midfield": 82,
        "defense": 81,
        "pace": 83,
        "physical": 81,
        "skill": 83,
        "age": 25.6,
        "value": 550,
        "league": "Bundesliga",
    },
    "eintracht-frankfurt": {
        "overall": 78,
        "attack": 79,
        "midfield": 78,
        "defense": 78,
        "pace": 79,
        "physical": 79,
        "skill": 77,
        "age": 26.9,
        "value": 380,
        "league": "Bundesliga",
    },
    "vfb-stuttgart": {
        "overall": 77,
        "attack": 78,
        "midfield": 77,
        "defense": 77,
        "pace": 78,
        "physical": 78,
        "skill": 77,
        "age": 25.7,
        "value": 340,
        "league": "Bundesliga",
    },
    "borussia-monchengladbach": {
        "overall": 76,
        "attack": 77,
        "midfield": 76,
        "defense": 76,
        "pace": 77,
        "physical": 77,
        "skill": 75,
        "age": 26.4,
        "value": 290,
        "league": "Bundesliga",
    },
    "wolfsburg": {
        "overall": 76,
        "attack": 76,
        "midfield": 76,
        "defense": 77,
        "pace": 76,
        "physical": 78,
        "skill": 75,
        "age": 27.2,
        "value": 280,
        "league": "Bundesliga",
    },
    # ===== SERIE A (20 teams) =====
    "inter": {
        "overall": 85,
        "attack": 86,
        "midfield": 85,
        "defense": 86,
        "pace": 81,
        "physical": 85,
        "skill": 86,
        "age": 28.1,
        "value": 820,
        "league": "Serie A",
    },
    "juventus": {
        "overall": 83,
        "attack": 83,
        "midfield": 83,
        "defense": 85,
        "pace": 79,
        "physical": 84,
        "skill": 83,
        "age": 27.8,
        "value": 680,
        "league": "Serie A",
    },
    "milan": {
        "overall": 83,
        "attack": 84,
        "midfield": 83,
        "defense": 83,
        "pace": 82,
        "physical": 83,
        "skill": 84,
        "age": 26.9,
        "value": 720,
        "league": "Serie A",
    },
    "napoli": {
        "overall": 84,
        "attack": 85,
        "midfield": 84,
        "defense": 83,
        "pace": 83,
        "physical": 82,
        "skill": 85,
        "age": 27.2,
        "value": 780,
        "league": "Serie A",
    },
    "roma": {
        "overall": 81,
        "attack": 82,
        "midfield": 81,
        "defense": 81,
        "pace": 80,
        "physical": 82,
        "skill": 81,
        "age": 27.5,
        "value": 520,
        "league": "Serie A",
    },
    "lazio": {
        "overall": 80,
        "attack": 81,
        "midfield": 80,
        "defense": 80,
        "pace": 81,
        "physical": 80,
        "skill": 80,
        "age": 27.8,
        "value": 480,
        "league": "Serie A",
    },
    "atalanta": {
        "overall": 80,
        "attack": 82,
        "midfield": 80,
        "defense": 78,
        "pace": 82,
        "physical": 79,
        "skill": 81,
        "age": 26.5,
        "value": 510,
        "league": "Serie A",
    },
    "fiorentina": {
        "overall": 78,
        "attack": 79,
        "midfield": 78,
        "defense": 78,
        "pace": 78,
        "physical": 78,
        "skill": 78,
        "age": 27.1,
        "value": 390,
        "league": "Serie A",
    },
    # ===== LIGUE 1 (18 teams) =====
    "paris-saint-germain": {
        "overall": 87,
        "attack": 90,
        "midfield": 87,
        "defense": 84,
        "pace": 88,
        "physical": 84,
        "skill": 90,
        "age": 26.2,
        "value": 1100,
        "league": "Ligue 1",
    },
    "monaco": {
        "overall": 80,
        "attack": 82,
        "midfield": 80,
        "defense": 79,
        "pace": 83,
        "physical": 78,
        "skill": 81,
        "age": 24.8,
        "value": 460,
        "league": "Ligue 1",
    },
    "marseille": {
        "overall": 79,
        "attack": 80,
        "midfield": 79,
        "defense": 79,
        "pace": 80,
        "physical": 80,
        "skill": 79,
        "age": 26.7,
        "value": 420,
        "league": "Ligue 1",
    },
    "lyon": {
        "overall": 78,
        "attack": 79,
        "midfield": 78,
        "defense": 78,
        "pace": 79,
        "physical": 77,
        "skill": 79,
        "age": 25.9,
        "value": 380,
        "league": "Ligue 1",
    },
    "lille": {
        "overall": 78,
        "attack": 79,
        "midfield": 78,
        "defense": 78,
        "pace": 80,
        "physical": 78,
        "skill": 78,
        "age": 25.4,
        "value": 390,
        "league": "Ligue 1",
    },
    # ===== EREDIVISIE (Top 6) =====
    "ajax": {
        "overall": 79,
        "attack": 81,
        "midfield": 79,
        "defense": 78,
        "pace": 81,
        "physical": 76,
        "skill": 81,
        "age": 24.2,
        "value": 420,
        "league": "Eredivisie",
    },
    "psv": {
        "overall": 79,
        "attack": 81,
        "midfield": 79,
        "defense": 77,
        "pace": 81,
        "physical": 77,
        "skill": 80,
        "age": 24.5,
        "value": 410,
        "league": "Eredivisie",
    },
    "feyenoord": {
        "overall": 78,
        "attack": 79,
        "midfield": 78,
        "defense": 77,
        "pace": 79,
        "physical": 78,
        "skill": 78,
        "age": 25.1,
        "value": 360,
        "league": "Eredivisie",
    },
    # ===== LIGA PORTUGAL (Top 5) =====
    "benfica": {
        "overall": 81,
        "attack": 83,
        "midfield": 81,
        "defense": 80,
        "pace": 82,
        "physical": 79,
        "skill": 82,
        "age": 25.3,
        "value": 520,
        "league": "Liga Portugal",
    },
    "porto": {
        "overall": 80,
        "attack": 82,
        "midfield": 80,
        "defense": 79,
        "pace": 81,
        "physical": 80,
        "skill": 81,
        "age": 25.8,
        "value": 480,
        "league": "Liga Portugal",
    },
    "sporting-cp": {
        "overall": 80,
        "attack": 82,
        "midfield": 80,
        "defense": 78,
        "pace": 82,
        "physical": 78,
        "skill": 81,
        "age": 24.9,
        "value": 490,
        "league": "Liga Portugal",
    },
    # ===== MLS (Top 10) =====
    "inter-miami": {
        "overall": 76,
        "attack": 79,
        "midfield": 76,
        "defense": 74,
        "pace": 77,
        "physical": 75,
        "skill": 78,
        "age": 28.5,
        "value": 280,
        "league": "MLS",
    },
    "la-galaxy": {
        "overall": 74,
        "attack": 75,
        "midfield": 74,
        "defense": 73,
        "pace": 75,
        "physical": 74,
        "skill": 74,
        "age": 26.8,
        "value": 190,
        "league": "MLS",
    },
    "lafc": {
        "overall": 74,
        "attack": 76,
        "midfield": 74,
        "defense": 73,
        "pace": 76,
        "physical": 74,
        "skill": 75,
        "age": 27.1,
        "value": 200,
        "league": "MLS",
    },
    # ===== BRAZILIAN SERIE A (Top 8) =====
    "palmeiras": {
        "overall": 77,
        "attack": 78,
        "midfield": 77,
        "defense": 77,
        "pace": 78,
        "physical": 78,
        "skill": 77,
        "age": 26.3,
        "value": 320,
        "league": "Brazilian Serie A",
    },
    "flamengo": {
        "overall": 77,
        "attack": 79,
        "midfield": 77,
        "defense": 76,
        "pace": 79,
        "physical": 77,
        "skill": 78,
        "age": 26.8,
        "value": 310,
        "league": "Brazilian Serie A",
    },
    "atletico-mineiro": {
        "overall": 75,
        "attack": 76,
        "midfield": 75,
        "defense": 75,
        "pace": 76,
        "physical": 76,
        "skill": 75,
        "age": 27.2,
        "value": 240,
        "league": "Brazilian Serie A",
    },
    # ===== SAUDI PRO LEAGUE (Top 5) =====
    "al-hilal": {
        "overall": 79,
        "attack": 82,
        "midfield": 79,
        "defense": 77,
        "pace": 80,
        "physical": 79,
        "skill": 81,
        "age": 28.9,
        "value": 450,
        "league": "Saudi Pro League",
    },
    "al-nassr": {
        "overall": 78,
        "attack": 81,
        "midfield": 78,
        "defense": 76,
        "pace": 79,
        "physical": 78,
        "skill": 80,
        "age": 29.2,
        "value": 420,
        "league": "Saudi Pro League",
    },
    "al-ittihad": {
        "overall": 77,
        "attack": 79,
        "midfield": 77,
        "defense": 76,
        "pace": 78,
        "physical": 77,
        "skill": 78,
        "age": 28.5,
        "value": 380,
        "league": "Saudi Pro League",
    },
}


def get_team_fifa_stats(team_name: str) -> Optional[Dict]:
    """
    Get FIFA stats for a team by normalized name

    Args:
        team_name: Team name (will be normalized)

    Returns:
        Dict with FIFA stats, or None if not found
    """
    # Normalize team name
    normalized = team_name.lower().strip()
    normalized = normalized.replace(" ", "-")
    normalized = normalized.replace("_", "-")
    normalized = normalized.replace("ü", "u")
    normalized = normalized.replace("ö", "o")
    normalized = normalized.replace("ä", "a")

    # Try exact match first
    if normalized in FIFA_TEAM_DATABASE:
        return FIFA_TEAM_DATABASE[normalized]

    # Try partial matching
    for db_name, stats in FIFA_TEAM_DATABASE.items():
        if normalized in db_name or db_name in normalized:
            return stats

    # Default stats for unknown teams (average lower-league team)
    return {
        "overall": 72,
        "attack": 72,
        "midfield": 72,
        "defense": 72,
        "pace": 72,
        "physical": 73,
        "skill": 71,
        "age": 27.0,
        "value": 150,
        "league": "Unknown",
    }


def get_all_teams_by_league(league_name: str) -> Dict[str, Dict]:
    """Get all teams in a specific league"""
    return {
        name: stats
        for name, stats in FIFA_TEAM_DATABASE.items()
        if stats.get("league") == league_name
    }


def get_top_teams(n: int = 20) -> Dict[str, Dict]:
    """Get top N teams by overall rating"""
    sorted_teams = sorted(FIFA_TEAM_DATABASE.items(), key=lambda x: x[1]["overall"], reverse=True)
    return dict(sorted_teams[:n])


# League averages for comparison
LEAGUE_AVERAGES = {
    "Premier League": {"overall": 77.8, "pace": 78.2, "physical": 79.1, "skill": 77.5},
    "La Liga": {"overall": 76.9, "pace": 77.8, "physical": 77.2, "skill": 78.4},
    "Bundesliga": {"overall": 76.5, "pace": 78.5, "physical": 78.0, "skill": 76.8},
    "Serie A": {"overall": 76.2, "pace": 76.9, "physical": 78.3, "skill": 77.1},
    "Ligue 1": {"overall": 75.1, "pace": 77.5, "physical": 76.8, "skill": 75.9},
}
